
import java.awt.Color;
import static java.util.stream.IntStream.range;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btComprobar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        lbSubTitulo = new javax.swing.JLabel();
        lbComprobar = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbPrimo = new javax.swing.JLabel();
        lbLista = new javax.swing.JLabel();
        lbSumaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btComprobar.setText("Comprobar");
        btComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprobarActionPerformed(evt);
            }
        });

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        lbSubTitulo.setText("Ingrese un numero:");

        lbTitulo.setText("Operaciones Basicas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(lbTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbSubTitulo)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btComprobar)
                                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbSumaP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                            .addComponent(lbPrimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSubTitulo))
                .addGap(18, 18, 18)
                .addComponent(btComprobar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPrimo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lbComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSumaP, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lbLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprobarActionPerformed
        // TODO add your handling code here:
        //perfecto
        int numero=Integer.parseInt(txtNum.getText());
        int suma=0;
        int i=0;
        
        for (i = 1; i==numero; i++) {
            if(numero % i ==0){
                suma+=i;
            }
            if(suma==numero){
                lbComprobar.setText("El Numero Es Perfecto");
                lbComprobar.setBackground(Color.GREEN);
            }else{
                lbComprobar.setText("El Numero No Es Perfecto");
                lbComprobar.setBackground(Color.RED);
            }
        }
        //primo
        boolean primo=false;
        int numPrimo=Integer.parseInt(txtNum.getText());
        if(numero<2){
            lbPrimo.setText("No es primo");
            lbPrimo.setBackground(Color.red);
        } else{
            primo=true;
        }
         for (i = 2; i < numPrimo; i++){ 
         
                 if (numPrimo % i == 0){
                     primo=false;
       }
          }
       if (primo){
        lbPrimo.setText("Es Primo");
        lbPrimo.setBackground(Color.GREEN);
        
    }else{
           lbPrimo.setText("No es Primo");
           lbPrimo.setBackground(Color.red); 
       //imprimir los numeros primos del numero ingresado la raiz de la suma
        for (int a = 1; a <= numPrimo; a++) {
            if(numero==1){
                
            }else{
                
            }
           }
        }
       //lista de numeros primo
      int numListap=Integer.parseInt(txtNum.getText());
       int contador = 2;
       boolean lisprimo=true;
       int sumaPrimos=0;
       double raiz;
       StringBuilder listaPrimos = new StringBuilder("La lista es: ");
       while (contador <= numListap) {// Reiniciamos el estado de primo para cada número
           lisprimo = true; 
          for ( i = 2; i * i <= contador; i++) {
        if (contador % i == 0) {
            lisprimo = false;
            }
        if (lisprimo) { // Si es primo, lo agregamos a la lista.
        listaPrimos.append(contador).append(", ");
        sumaPrimos += contador;
    }
    contador++;
    }
          raiz=Math.sqrt(sumaPrimos);
          lbLista.setText(listaPrimos.toString());
          lbSumaP.setText("La raiz cuadrada de la suma es: "+raiz);
// Mostramos la lista de primos en el JLabel.
}
    }//GEN-LAST:event_btComprobarActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComprobar;
    private javax.swing.JLabel lbComprobar;
    private javax.swing.JLabel lbLista;
    private javax.swing.JLabel lbPrimo;
    private javax.swing.JLabel lbSubTitulo;
    private javax.swing.JLabel lbSumaP;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
